### ISSUE TITLE
We need abstract identifiers for our artifacts to not couple ourselves to a specific programming language and be able to not tie ourselves to types in storage like Event Store

### ISSUE THREAD

**Issue by einari** [dolittle/DotNET.SDK#25]
parent of #21

**Comment by einari** [comment]
# Design Discussion

The goal of this is have an abstract representation of artifacts that allows us to identify them consistently inside applications - meaning that their location is important.
This representation is something we at times save, for instance events in an eventstore.
Previously we used to save .NET CLR type information - like the `AssemblyQualifiedName` of a type.
This poses a couple of problems:

* Its a .NET Type - what if another bounded context, or even another application - built with a different programming language consumes these - how would they be identified
* Restructuring, sometimes one restructures - but the logical location is the same, its just structurally in the language used different
* Refactoring - this is probably the hardest problem to deal with, and not the highest on the priority list. But if one change the name of an artifact, how can we have a logical consistent representation it.

When originally designing this system, the goal was to avoid having to explicitly create Guids for your types. This does not feel natural to have to do for potentially every type in a system. It would be the perfect thing for identifying something - guaranteed uniquely. But it adds the foreign construct of having to have either an attribute in C# on every type that you have to add that needs to be identified. Today we're using this for identifying the following types in C#:

* Commands
* Events
* Event Processors

In the future this will expand into things like validation rules, business rules, security descriptors etc. It quickly becomes something that spreads across to every corner of a system. It also poses the question of how would this be in other languages as well. JavaScript, TypeScript now have annotations - but what is the correct construct for something like this in Python and Ruby or others. 
However, at runtime when an application is deployed and we will register it in the Application Registry, there will be a unique identifier registered for the artifacts in the deployment registered in the topology. 
Personally I'd prefer to avoid having to have `Guids` explicitly put in - no doubt it would be better for the developer if this was just magically happening behind the scenes. We don't need to tackle this particular problem right now, as it really does not become a problem until we need to refactor.
With the talk about migrators and generations of types, there might be a correlation here. We could come up with tooling that helps us do this - the problem is only a visible when changes are being made and you're deploying, meaning that we need something that maps from the logical representation of something to a new meaning of it. The first time one deploys, one establishes the logical representation of an artifact and any subsequent deploys could then be mapped into this logical representation. This is a topology question. However, when we are storing things - storing the actual application artifact identifier could be and probably is completely wrong. Storing a `Guid` here would make it more consistent and adding flexibility in the form of us being able to change the logical representation if we wanted as well without having to change events or having to add another layer of mapping between what is in the eventstore and what is in the topology which then is mapped to what is at runtime.

## Structure

For structure and how we build this. This was originally designed to be very flexible, allowing anyone to build their own structure with their own structural concepts.
There are multiple layers to this problem. One is the application topology and allowed structure, another is what the identifiers hold - which is the actual location.

### Fundamentals

The following responsibilities are in fundamentals:

* Representation of the identifier and its location and generation of the type it represents.
* Application and structure configuration - the allowed structure
* Conversion between the object representation and something like a string representation.

### Runtime

The following responsibilities are in the runtime:

* Application registry
* Application topology for each version of a bounded context

### SDK

The following responsibilities are in the sdk:

* Application structure mapping from language specific structure location to application artifact identifier

### Building Blocks

We are trying to formalize and enforce structure and trying to add flexibility to it. How much flexibility is something we need to think hard about.
There could also be a case for not giving flexibility at all and let that be something we can add later, if we want to.
By removing flexibility, we would gain more control over this and learn more what works faster.

Our current definition contains the following structural building blocks:

| Type | Description | Relationship |
| ---- | ----------- | ------------ |
| Application | An application is the top level and is registered in the tenants account | Top Level |
| Bounded Context | Every application can have one or more bounded contexts. | Child of application |
| Module | Within every bounded context, we currently define module as optional - you can have zero or more | Child of bounded context |
| Feature | Within a bounded context or a module you can have one or more features | Child of bounded context or module |
| Sub Feature | Within a feature you can have zero or more sub features - this is recursive | Child of feature or sub-feature |

#### Bounded Context

In DDD a bounded context is defined as the place with a ubiquitous domain language. There are other aspects as well, and below is
what we've discussed so far for identifying it:

* Ubiquitous language
* What domain experts are being represented
* Deployment target - where will it be deployed. Example of this would be; edge (Ship) vs cloud.
* Source of truth - there can only be one source of truth, two bounded contexts should never produce same events
* The things that belong together - should be together

All these things lead also to a couple of technical things

* Deployment - When deploying, you deploy the bounded context in isolation
* Isolation - e.g. one event store and one database per bounded context (tenant segregation as a second layer to this)

Deployment is not the same as what is running and how the landscape of runtime environment is.
So if the container orchestration aspect of this would have multiple running artifacts, for instance divided by tiers (Frontend, Domain, Read, Event Processing),
they would still use the same eventstore and database underneath, context aware with tenant as very important.

The goal is to avoid friction, enabling individual parts of the system to move forward at independent paces with decoupled release cadence.
It allows for scaling your team - it does not mean you will scale. You could have one team maintaining multiple bounded contexts, and then just have
the benefit of being able to release independently. But the potential lies within to then have multiple teams that can move independently.
The point here is that one does not start designing it from a team perspective, but by having a clear definition of how to identify a bounded context -
one would implicitly enable this scenario when and if needed or wanted.

##### eCommerce - Example of bounded contexts

Instead of produce being the single entity used across, there is clearly different languages and facets of product that has explicit use cases in the respective bounded contexts:

* Warehouse - interested in the location in the warehouse, weight and dimensions
* Purchasing - interested in the net price and what gross price
* Delivery - interested in the weight, dimension and address to deliver to
* Shop - interested in product titles, descriptions, details - pictures, stock

##### eCommerce - Red Cross CBS

* Administration - setting up projects and health risks
* User management - setting up organizational structures
* Volunteer reporting - registration of cases
* SMS ingress - a technical language, representing the endpoint

#### Module

A construct we have yet to formalize. Inspired by business components agreed upon by Greg Young and Udi Dahan - read more [here](http://udidahan.com/2012/02/10/udi-greg-reach-cqrs-agreement/).
This is something we have not had practice of doing.
But the thinking thus far is as follows:

* It belongs in a bounded context
* There can be multiple of them
* One module is separated from another - other aspect of the domain in the bounded context
* Every module in a bounded context represents the same domain expert
* It is not a deployable unit - meaning that changes in this means a deployment of the bounded context

#### Feature & Sub features

A feature sits inside the system representing a concrete implementation. It could sit inside a bounded context or inside a module by current definitions.

Take eCommerce as an example, this could be a structure:

```
+-- Shop (Bounded Context)
  +-- Catalog (Module)
  | +-- List (Feature)
  | +-- Details (Feature)
  +-- Cart (Module)
    +-- Glance (Feature) - shows count at the top for example
    +-- Details (Feature)
```

Within features you might at time want to break up into more fine-grained sub-features composed by the feature itself.
Good examples of this are typical detail views that could for instance hold a tabstrip and every page be a sub-feature.
You'd then implement each of these independently.

**Comment by smithmx** [comment]
There are two basic approaches as far as I see it.  Either we 

1. define the structure and assign artifacts to the structure at build time

2. require the developer to identify artifacts at design time.  

The big trade-off is between intrusiveness and refactorability.  

The least intrusive way is to infer artifacts from their position in the structure.  The structure can be defined by the user or implicit (from solutions, projects, folders, etc.).  This approach runs smack into the problem of versioning.  How do I say that eventv2 is the second generation of eventv1 without having some kind of code representation of v1?  Nobody wants to have all classes hanging around for all time, or be forced to add a new class when you just want to amend the existing one.  We can always version things through migrators - how do you declare a new version? You write a migrator from the old version to the new one... but we still need to identify what you are migrating to and from!  In code terms these will be PropertyBag to PropertyBag, but we need to know what these represent.  You still need an artifact identifier for the domain concept you are representing!  I think it's clear that we need a persistent application structure that we can use to consistently identify artifacts and with which we can associate types/locations in some fashion.

How do we come up with this structure?  The problem with using implicit position is refactorability, the problem with forcing the developer to be explicit is that it is intrusive.  It can get in the way of them working.  When I write a new event, do I really want to also have to register this new event as an application artifact is some way (Fluent Interface / attribute)?  Probably not but that doesn't mean that you shouldn't have to do it.  We should seriously consider how easy we want to make it to create artifacts (commands, events, read models, etc) if they then effectively have to exist for the rest of time.  We can do automatic migrations of course, but over time there will be a buildup of identifiers and migrators.  A bigger issue for me is that it would interfere with how I develop.  I might just be exploring a feature at this point and the commands, aggregates and events that I'm coming up with are expected to change.  I don't want to settle on these concepts or commit to them yet.  This suggests there has to be a "now I'm happy I'm at version one" stage which acts like a "commit" to the application structure.

My first thoughts are that we have a default registration that uses much like what we have just now but this is supplemented by an explicit assignment in some way.  What we need to do is keep a copy of the "committed" structure and compare that to the built one on each build.  We can then throw exceptions or issue warnings if the structure has changed.  We'd probably have to allow users to write Ignores or Deletes so that you didn't get constantly annoyed by the local build process.  It would also have to output a code representation that could be used in our code, so I could write new ship_registered_migrator(commodity_planner.commodities.ship_registered,2,3).  If we could verify this at build time rather than runtime, that would be a major plus.

I don't agree that refactoring is not a high priority.  We might not need to implement it immediately but we absolutely have to have a plan for how it would work or else our design is wrong.  You can be naive in implementation, you can't be naive in interface / design.

The more I think about it the more worried I get about creating so many artifacts easily and without much thought.  Sure, it's great for rapid development and prototyping but I'm concerned it will become bloat and weight on the system.  This is something we don't need to address now but just something we should keep in mind.  I suspect we might have to loosen some of our constraints (e.g. allow you to delete event streams at least from dev and test, allow you to migrate an event stream, aggressive use of snapshots, etc).

**Comment by einari** [comment]
Don't get me wrong; catching the ability to refactor is super important and we don't want to paint ourselves in a corner. I was more thinking how to prioritise the effort of this as it is a bit of an unchartered territory. 

I think there needs to be explicitness - but the explicitness only really needs to be there when there is a breaking change in the structure, and it should be easy and consist in doing this. 

The initial version of a a structure / topology can be deducted from the configured structure mapped to the running code. As you then say, any breaking change from that can be caught with tooling - preferably as soon as possible. This will differ from programming language to programming language what is the right way. There should at the very minimum be a validation step as part of our **continuous improvement** pipeline that would prevent a deployment to be put into production before the right migration steps are in place for the breaking changes. It ties into the generation of types as well. 

With refactoring in mind, as I mentioned; we should store Guid representations of the artifacts - not a string that potentially could change if structure is changed or items totally moved. During the first initial registration in the topology it would get this ID assigned. 

Anywho..  In light of vacation time - can we get back to all this in August and park any work on this, as this really sounds more like a whiteboard session with us.

**Comment by smithmx** [comment]
You know what, this would all be so much easier if the application structure was an Aggregate Root and we had commands and events. :-)

**Comment by einari** [comment]
👍 
That is a very good point. Thats how I've been thinking of it from the write side when you deploy these things - the platform should just dogfood itself - we need full audit of this anyways and makes sense to do that. Its even commands coming in with business rules governing what is allowed or not..   

Its then a lot easier to model this - instead of trying to come up with the read models that we've effectively been discussing.. 

My head is now a bit blown :)    Thanks!  This is much easier - the requirements then becomes much clearer. 

Lets use July to think about this even more - I'll start work on the build pipeline, which is going to need to register these things and should then somehow do that towards an aggregate / eventsource.

**Comment by einari** [comment]
Here is an opportunity ; we could event storm the entire process end to end.

**Comment by woksin** [comment]
In the past week we've been running into a lot of trouble, mainly with the DotNET.Fundamentals project. All the problems we were having were related to the fact that the essential core of our platform is overcomplicated and too generic. 

My impression is that the core was built to be able to handle a lot of different stuff, be a "jack-of-all-trades" kind of construction. But in reality, the things that it really should be doing are really specific things that shouldn't be generic 

To mention one specific thing, I think there are way to many interfaces. 
For example we have an interface IApplication which really is just a bag of three properties. IApplication in itself defines no behaviour other than it should be Equatable and Comparable to itself. This thing specifically gave us some hard to find bugs because we had another interface, IApplicationArtifactIdentifier which had an IApplication property, when we were comparing two IApplicationArtifactIdentifiers we ran into a problem where the result was always false because the equality check on IApplication was done using the != operator. The one and only concrete instantiation of IApplication, Application, did define the static operators == and !=, but those procedures were never called because we were doing the check on the interfaces, not on the concrete types.

**Comment by einari** [comment]
Let's hold off on changing anything before we've had a design session with whiteboards and sticky notes. 
There are a lot of thoughts that went it to this but it might not all be needed and there is a potential for simplification at this level. We just need to make sure we don't lose out on what we're trying to accomplish.

**Comment by einari** [comment]
Conclusion after design meeting
![img_2008](https://user-images.githubusercontent.com/134365/43139432-f9f76e48-8f51-11e8-94c0-dc6c0b76d5fd.jpg)
