### ISSUE TITLE
When configuring mapping from CLR type information to AAI, it needs to validate that it has the required parts of the structure that gets configured for the application

### ISSUE THREAD

**Issue by einari** [dolittle/DotNET.SDK#3]
child of #25

**Comment by woksin** [comment]
Isn't the BoundedContext a non-optional fragment of an Application structure? And if so, isn't this an issue for Fundamentals?
@einari

**Comment by einari** [comment]
Yes and no..   
We need validation in Fundamentals when converting for instance from a string representation to an AAI - so I've added an issue for that [here](https://github.com/dolittle/DotNET.Fundamentals/issues/24).

When we build the application structure, thats when we say what is required or not. 

This issue probably needs a good renaming - didn't win the 🥇 on accuracy. 
What we're trying to do here is to validate the mapping from C# type information to the structure that it includes all the aspects that gets configured in the application structure and this is an SDK specific thing. Renaming the issue to reflect this.

**Comment by woksin** [comment]
Instead of doing this, wouldn't it be better if we did a validation when we construct every ApplicationArtifactIdentifier?

In my opinion what we should do is, in the startup process of the application (started on implementing this system in PR #32):
- Discover every type that will become an ApplicationArtifactIdentifier.
- Map the AAI up to its corresponding Type
- Keep a dictionary in memory for mapping between them

If we do this we can throw an Exception at startup of the application if we discover an AAI with a weird Location, saying "Hey, something is weird about your structure mapping. It should require <blah> and <blah>"

Thoughts, @einari , @smithmx ?
